// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLocalIPs() {
  return window['go']['main']['App']['GetLocalIPs']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function IsPhoneConnected() {
  return window['go']['main']['App']['IsPhoneConnected']();
}

export function OpenDownloadsFolder() {
  return window['go']['main']['App']['OpenDownloadsFolder']();
}

export function SendFileToPhone() {
  return window['go']['main']['App']['SendFileToPhone']();
}

export function SetMiniMode(arg1) {
  return window['go']['main']['App']['SetMiniMode'](arg1);
}

export function StartServer(arg1) {
  return window['go']['main']['App']['StartServer'](arg1);
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}
