// Generated by scripts/brand/mark.cjs. Do not edit by hand.
// The Streamline A: three smoke filaments rising over a peak (outer → inner),
// crossed by the orange streamline files ride on. 64×64 box.
export const STRANDS = [
  'M5 55C11.5 55 25.76 17 32 8C38.24 17 52.5 55 59 55',
  'M11.2 55C17.7 55 27.2 24 32 15C36.8 24 46.3 55 52.8 55',
  'M17.4 55C23.9 55 28.63 31 32 22C35.37 31 40.1 55 46.6 55'
] as const;

export const CROSSBAR = 'M-4 41.2C12 41.2 22 38.8 32 38.8S52 41.2 68 41.2';
