// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetLocalIPs():Promise<Array<main.NetworkInterface>>;

export function GetServerStatus():Promise<main.ServerStatus>;

export function OpenDownloadsFolder():Promise<void>;

export function StartServer(arg1:string):Promise<void>;

export function StopServer():Promise<void>;
